In [2]:
# https://nswpropertysalesdata.com/
#https://www.valuergeneral.nsw.gov.au/bulk_psi/bulk_psi_header


import numpy as np 
import pandas as pd 
import os
#from chart_studio.plotly.offline import init_notebook_mode, iplot
#import chart_studio.plotly.plotly as py
#import chart_studio.plotly.figure_factory as FF
#import chart_studio.plotly.plotly as py
#from chart_studio.plotly import tools
#from chart_studio.plotly import tools
#import chart_studio.plotly.graph_objs as go

import chart_studio.plotly as py

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

import matplotlib.pyplot as plt
import seaborn as sns
import folium
from folium.features import DivIcon
from folium.plugins import HeatMap
import warnings
import datetime
import squarify
warnings.filterwarnings("ignore")
# init_notebook_mode(connected=True)

from datetime import date
dtm = datetime.datetime(2021, 1, 1, 0, 0, 0, 000000)

pd.set_option('display.max_colwidth', 100)

In [3]:
datah = pd.read_csv("/home/youwombat/Projects/House/202205-House-Search/nsw-property-sales-data-updated20230110.csv",index_col=0)

In [4]:
datah

,Property ID,Download date / time,Property name,Property unit number,Property house number,Property street name,Property locality,Property post code,Area,Contract date,Settlement date,Purchase price,Zoning,Primary purpose,Strata lot number
0,3474431.0,20210412 01:00,NaN,5,195,Aberdare St,Kurri Kurri,2327.0,NaN,2021-03-11,2021-04-08,380000,NaN,Residence,5.0
1,4206979.0,20210412 01:00,NaN,NaN,18,Lockwood St,North Rothbury,2335.0,578.00,2021-02-22,2021-04-06,610000,R1,Residence,NaN
2,4226730.0,20210412 01:00,NaN,NaN,35,Harrow Cct,Greta,2334.0,2127.00,2021-03-09,2021-04-06,345000,R2,Vacant land,NaN
3,8505.0,20210412 01:00,NaN,NaN,4,South Ave,Cessnock,2325.0,771.40,2021-03-10,2021-04-07,405000,B4,Residence,NaN
4,8690.0,20210412 01:00,NaN,NaN,51,View St,Cessnock,2325.0,744.40,2021-02-04,2021-04-08,590000,R3,Residence,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2214054,3210837.0,20220214 05:56,NaN,NaN,205,Rochford St,Erskineville,2043.0,NaN,2021-07-23,2021-09-07,800000,NaN,Residence,7.0
2214055,4210735.0,20220214 05:56,NaN,517,303,Botany Rd,Zetland,2017.0,62.00,2022-01-27,2022-02-04,875000,NaN,Residence,30.0
2214056,4278203.0,20220214 05:56,NaN,2505,60,Bathurst St,Sydney,2000.0,58.00,2017-06-30,2022-02-07,1180000,NaN,Residence,89.0
2214057,2140190.0,20220214 05:56,NaN,51,146,Pitt St,Redfern,2016.0,NaN,2021-12-11,2022-02-07,1280000,NaN,Residence,51.0
2214058,2130091.0,20220214 05:56,NaN,NaN,514,King St,Newtown,2042.0,125.36,2021-12-03,2022-02-08,1705000,B2,Shop,NaN